name = "pydantic-errors-redirect"
main = "src/index.ts"
compatibility_date = "2023-04-24"
account_id = "d6252a570c309c113744c9e11317e271"
route = "errors.pydantic.dev/*"

[vars]
GITHUB_SHA = "unknown"
